---
title: Innherred Judo og BJJ
timezone: UTC
collections:
  menneskene:
    title: Menneskene
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Opplev morsom og god trening for alle
owner: IJB
first_published: 2016
email: ijudobjj@gmail.com
baseurl: ''
url: http://www.innherredjudobjj.no
social:
  facebook-official: https://www.facebook.com/innherredjudobjj/
  email: "/index.html#kontakt"
  instagram: http://instagram.com/innherredjudoogbjj
  youtube-square: https://www.youtube.com/channel/UCYglIAHSwPWnh_Ipse9NyBg
markdown: kramdown
